# Generated by Django 4.0.2 on 2023-01-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=115)),
                ('desc', models.TextField()),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
